apiVersion: v2
name: mastodon
description: Mastodon is a free, open-source social network server based on ActivityPub.

# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 9.8.2

# renovate: image=ghcr.io/mastodon/mastodon
appVersion: v4.3.3

dependencies:
  - name: postgresql
    version: 16.0.4
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled

  - name: elasticsearch
    version: 19.21.2
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: elasticsearch.enabled

  - name: redis
    version: 20.1.4
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
