apiVersion: v2
name: mastodon
description: Mastodon is a free, open-source social network server based on ActivityPub.

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 4.2.0

# renovate: image=ghcr.io/mastodon/mastodon
appVersion: v4.1.4

dependencies:
  - name: postgresql
    version: 12.6.0
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
  - name: elasticsearch
    version: 19.10.6
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: elasticsearch.enabled
  - name: redis
    version: 17.14.6
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
