apiVersion: v2
name: mastodon
description: Mastodon is a free, open-source social network server based on ActivityPub.

# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 5.1.0

# renovate: image=ghcr.io/mastodon/mastodon
appVersion: v4.2.8

dependencies:
  - name: postgresql
    version: 13.4.6
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled

  - name: elasticsearch
    version: 19.19.3
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: elasticsearch.enabled

  - name: redis
    version: 18.17.0
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
